add commands defragmentation

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,14 +1,13 @@
 #!/usr/bin/env bash
 
-VER="1.4.7"
-LOG_FILE="$HOME/.cache/jaylog.txt"
-[[ -f "$LOG_FILE" ]] || touch "$LOG_FILE"
+VER="2.0"
 
-ALERT="[!]"
-ERROR="[x]"
-OK="[✓]"
-WARNING="[*]"
-CONTINUE="[>>]"
+REAL_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
+REAL_HOME=${REAL_HOME:-$HOME}
+
+MODULES_DIR="$REAL_HOME/.config/jay/modules"
+LOG_FILE="$REAL_HOME/.cache/jaylog.txt"
+CONFIG_DIR="$REAL_HOME/.config/jay"
 
 CYAN='\033[0;36m'
 GREEN='\033[0;32m'
@@ -16,16 +15,11 @@ YELLOW='\033[1;33m'
 RED='\033[0;31m'
 NC='\033[0m'
 
-step() { echo -e "${CYAN} $CONTINUE ${NC}${1}"; }
-success() { echo -e "${GREEN} $OK ${NC}${1}"; }
-error() { echo -e "${RED} $ERROR ${NC}${1}"; exit 1; }
-
-logger() {
-    local tag="$1"
-    local info="$2"
-    local date_str=$(date "+%H:%M - %d/%m/%Y")
-    echo "($date_str) | $tag | $info" >> "$LOG_FILE"
-}
+ALERT="[!]"
+ERROR="[x]"
+OK="[✓]"
+WARNING="[*]"
+CONTINUE="[>>]"
 
 msg01() {
     echo -e -n "${CYAN} $ERROR ${NC}" && echo "argumento invalido '$VAR'" | tr -d "-"
@@ -39,6 +33,34 @@ msg02() {
 
 msg03() {
     echo -e "\n ${CYAN}-> JAY (Just Another Yogourt) - Version $VER ${NC}\n"
+}
+
+msg04() {
+    echo -e "${RED}$ERROR Módulo base não encontrado${NC}\n -> saindo com status 1"
+    exit 1
+}
+
+[[ -f "$LOG_FILE" ]] || touch "$LOG_FILE"
+
+if [[ ! -f "$MODULES_DIR/base" ]]; then
+    msg04
+fi
+
+source "$MODULES_DIR/base"
+
+[[ -f "$MODULES_DIR/cache" ]] && source "$MODULES_DIR/cache" || MOD_1="0"
+[[ -f "$MODULES_DIR/search" ]] && source "$MODULES_DIR/search" || MOD_2="0"
+[[ -f "$MODULES_DIR/extra" ]] && source "$MODULES_DIR/extra" || MOD_3="0"
+
+step() { echo -e "${CYAN} $CONTINUE ${NC}${1}"; }
+success() { echo -e "${GREEN} $OK ${NC}${1}"; }
+error() { echo -e "${RED} $ERROR ${NC}${1}"; exit 1; }
+
+logger() {
+    local tag="$1"
+    local info="$2"
+    local date_str=$(date "+%H:%M - %d/%m/%Y")
+    echo "($date_str) | $tag | $info" >> "$LOG_FILE"
 }
 
 help_message() {
@@ -69,25 +91,6 @@ tester() {
     fi
 }
 
-remove_orphans() {
-    step "Buscando pacotes órfãos..."
-    ORPHANS=$(yay -Qdtq)
-    if [[ -n "$ORPHANS" ]]; then
-        step "Removendo: $ORPHANS"
-        yay -Rsn $ORPHANS
-        EXIT_CODE=$?
-        if [[ $EXIT_CODE -eq 0 ]]; then
-            success "Órfãos removidos com sucesso."
-            logger "[ORPHAN REMOVED]" "ALL_ORPHANS"
-        else
-            error "Falha ao remover órfãos."
-        fi
-    else
-        success "Nenhum pacote órfão encontrado."
-    fi
-    exit 0
-}
-
 [[ -z "$1" ]] && usage
 
 RAW_CMD="$*"
@@ -101,19 +104,58 @@ fi
 
 case "$1" in
     "-") msg02 ;;
-    install|-i|-S) tester; CMD="-S"; TAG="[INSTALLED]"; FLAT_CMD="install flathub" ;;
-    remove|-rm) CMD="-R"; TAG="[REMOVED]"; FLAT_CMD="uninstall" ;;
-    refresh|-r) tester; CMD="-Syy"; TAG="[REFRESHED]" ;;
-    update|-u) tester; CMD="-Syu"; TAG="[UPDATED]"; FLAT_CMD="update" ;;
-    search|-s) tester; CMD="-Ss"; TAG="[SEARCHED]"; FLAT_CMD="search" ;;
-    query|-q) CMD="-Qs"; TAG="[LOCAL_QUERY]" ;;
-    cache|-c) CMD="-Sc"; TAG="[CACHE CLEAN]" ;;
-    slog|-sl) [[ ! -s "$LOG_FILE" ]] && { echo "Log vazio."; exit 0; }; column -t -s '|' "$LOG_FILE"; exit 0 ;;
-    clog|-cl) > "$LOG_FILE"; success "Logs limpos."; exit 0 ;;
-    orphan|-o) remove_orphans ;;
+    install|-i|-S) ins ;;
+    remove|-rm) rmv ;;
+    refresh|-r) rfs ;;
+    update|-u) upd ;;
+    search|-s)
+        if [[ "$MOD_2" == "0" ]]; then
+            echo "$WARNING Não foi possivel carregar o módulo search."
+            exit 1
+        else
+            searcher
+        fi
+    ;;
+    query|-q)
+        if [[ "$MOD_2" == "0" ]]; then
+            echo "$WARNING Não foi possivel carregar o módulo search."
+            exit 1
+        else
+            query
+        fi
+    ;;
+    cache|-c)
+        if [[ "$MOD_1" == "0" ]]; then
+            echo "$WARNING Não foi possivel carregar o módulo cache."
+            exit 1
+        else
+            clr_cache
+        fi
+    ;;
+    slog|-sl)
+        [[ ! -s "$LOG_FILE" ]] &&  echo "Log vazio." && exit 0
+        column -t -s '|' "$LOG_FILE" 
+        exit 0
+    ;;
+    clog|-cl)
+        > "$LOG_FILE"
+        success "Logs limpos."
+        exit 0
+    ;;
+    orphan|-o)
+        if [[ "$MOD_3" = "0" ]]; then
+            echo "$WARNING Não foi possivel carregar o módulo extra."
+            exit 1
+        else
+            remove_orphans
+        fi
+    ;;
     -v|--version) msg03; exit 0 ;;
     -h|--help) help_message ;;
-    *) VAR="$1"; msg01 ;;
+    *)
+        VAR="$1"
+        msg01
+    ;;
 esac
 
 ACTION="$1"
